title: Champagne & Coding
author: Jasmine Carter
email: jlcart6@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This blog is all about me, along with two of my favorite things...champagne and coding! I have a 6 year old french bulldog, pizza makes me happy and fuzzy socks and movies make the happiest! 
  
  I have spent the last 10 years of my career in finance, where I've gained interpersonal skills, experiences in problem solving and adaptable communication. I was finding a lack of challenges and each day my desire to be more creative grew.
  
  That's when I decided to go to the We Can Code It Bootcamp and I immediately got to experience and fulfill all the challenges I have been wanting from day one. I am getting training in computational thinking, back end computer programming and front end web development.

# social links
linkedin_username: JasmineCarter927
github_username:  JasmineCarter

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
